# --- !Ups

ALTER TABLE location ADD COLUMN website VARCHAR DEFAULT NULL;
ALTER TABLE location ADD COLUMN phone VARCHAR DEFAULT NULL;
ALTER TABLE location ADD COLUMN comment VARCHAR DEFAULT NULL;
ALTER TABLE location ADD COLUMN link VARCHAR DEFAULT NULL;

# --- !Downs

ALTER TABLE location DROP COLUMN website;
ALTER TABLE location DROP COLUMN phone;
ALTER TABLE location DROP COLUMN comment;
ALTER TABLE location DROP COLUMN link;
