language: scala
jdk: oraclejdk8
scala:
- 2.12.2
node_js: '6'
notifications:
  slack: whatsontoday:K22qCdNZ7GFj20Hrt8hU3DoS
env:
  global:
  - USER="whats-on-today-bot"
  - EMAIL="whats-on-today-bot@whats-on.today"
  - REPO="WhatsOnToday.github.io"
  - GH_REPO="github.com/WhatsOnToday/WhatsOnToday.github.io.git"
  - secure: isBfSQxqlC31yZiT0Jb9Oe/BOxKz7rEBDsMuYinKgQe+24w8Qm4GGKKiqnoqbihaP+MSwlSoL6kfm8XsD8Vq4VAZJqPJUiZ8ZWLkwqbNjCGbn9VsPSqg//bVmGYBAmZQnW/5dRyK0LCCneXkywvo9+G2TX5xzR1kMBEbTccQrJHi/DUzQp3q/UP3TECSAoQIR3wDZcUEWC/bjMjvKjYju++BHY5j3rUMCpmHnuxK9SJsIG8GwqmAqxZK/RYgpixd4p8Mfy2u0Eqgp+81Ek1BNb4ncq/dqe9KgeYNdpKZBEQPQc1Gb/AZaXSdZ/L1tDQiKCAB6ZxZTh2zldh9AMQp3ilQKBnJwjHB4Y49SinntYPNh/d0mDo1+EPeYCtLGO+ymnyPZSRbstoOyRMTis7iMNeFIFpCeL0HGoODcA1LJH0/bxpmB3Xi4rWSoMUSQkS/ZrQbf/VKL/gvGm37cLSRZSrCjiv7VM2dvdNt8ox0m7JLNkfiTQfeGubW/jTM94bqD/s5Avvl9boJObgm36E692lgjOFCuHP6OGKea9oqNiH9WojNYmI9gmf1uLfIwmpmLOVEAJsoeZvtKq3Th9O+TNUmQbxUrYw/0qm9/NDKQ0g5b2nzFfd4nT1LwEAVncyBCLX/XsQq72SxMGi/PtpxvrXLNFlphktMdiXXdXlBoJU=
  - secure: Yrf18kn2JXkhVrAx+GJLOhNWUNLucoOYisY0A7Xm3kEo3zNcofZ8xvktgHiwhtQLlUa95vHOyQTIdUYfkGJMD/btXzR4Q24Tu16IamsB3R8LKGzuGuKuXBmxsoaZyyk/U1jm9mtFle6IynV98P4zSWzO60pK3Anr+flCzDSjMz8nMORp19bjr54kr/Ebqk5fy1rIAe5B7NPtJiJKt+KAimmQ6ZhqknPdkZMDp2UO0Gfyj3Gx2+jJmbYCoXF53SGYoCHtWcfYjUjvn3WFMDqhtN678e2C/Nj0ShsAsET4/XpUs/y8nc5s1O+oXL1hD6Kowc7a8v0DeJciEXmImrbQV8rcOAjpqXjw4oZm6G+pXGnUajl94TgrJqR2UL4f2FZMUt+4hSGgPDEsOL75rxG82UrdN7AmucXnvgD3ye6f/U0P6vBQhPS0/a64ugnQuQabz47YhaBEc0gHD+9KJsCMFDttem8uf4hcTwwuDSZXTzlzJznO+eOB8K7iP876nbDzIU+eD0xmg4pVTNbLiYNl0FO/xwo/+3p46Hjr0JQTfQNU4Hz8/eQr0zdZGnftyl5klLxz+tNVcWKew+XB5fsZGcj+vAy9uGQrkiuj5a/FsI0vd6BsYy3V6SSRFbXeJJxHlBah+0F0Ft5CDtQm8Hzoupbcb4qXkBlXC7i8B5ULzxc=
services:
- postgresql
before_script:
- psql -c 'create database "WhatsOnDBTest";' -U postgres
script: "./travis/build.sh"
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
  - "./webapp/node_modules/"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
after_success: "./travis/success.sh ./travis/deploy.sh"
