language: scala

jdk: oraclejdk8

scala:
   - 2.12.2

notifications:
    slack: whatsontoday:K22qCdNZ7GFj20Hrt8hU3DoS

env:
  global:
  - USER="whats-on-today-bot"
  - EMAIL="whats-on-today-bot@whats-on.today"
  - REPO="WhatsOnToday.github.io"
  - GH_REPO="github.com/WhatsOnToday/WhatsOnToday.github.io.git"
  - secure: sdbLsuqUEJk09SN3MBRsmGjAp/fHSbxDaNmm7HhkRjNYAdM9J6evJ/1RlEqO1ap4jvctdmg6EhFmr3jIcjsjQ2kAc81nYQC9FnnCt8eZJFMaKK9H5VG9S4LednbaaQWQgHf+8usgfQed8ZQlfP0mEzVvzuy4yk5VLqOCOMxyawOjLZo6jcur9dQzvy00AGlkKm2mEqpSKzfWnek81Mwwa6sg2fWA7oCRa2HOlg/GBph97I+xEs1VrgHZTRXpsflZeaFTGwjhsgLc59MQ3OxhAgcz4RIpEgjSb1xrsZx6NIiyYWiAqN9BALxvyDul2P9JK2vwQ5+m+42JG7m/y6B6bvMmIkEktw5pm6Aotse/oSyjaSD+OoyaEyuxFn+Wniwl0ARgxVYMQNu+iBQ2nISgz7pbvPu6Tuz8xyDCXYEZdABEp07o56T2zgWf3W7aoU6C4uihcAoKcS1FeXkmS5QAI5Il9UVtk/dPx0+2qX2VV72PxYkW4+btdQzw6LAFk+g0PNdX8+Jz4HglQpUlsbe5AHLIVf9896cJFIxEmDOjjp72ehqvzD+SBQA1QJoC01PEewEsHIq6j0J1XdYLSsZc+0+XI5Gbmqe1xwSKo7+KgVl8DgYepw+Fn03yLQRIVHZv4OjOcQuhRrZF1wM852Sp56eMZTfcgRrm2zj+Zqcw9yw=
services:
  - postgresql

before_script:
  - psql -c 'create database "WhatsOnDBTest";' -U postgres

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

after_success:
  - cd $TRAVIS_BUILD_DIR
  - sbt swagger
  - git clone git://${GH_REPO} $HOME/$REPO
  - cp $TRAVIS_BUILD_DIR/target/swagger/swagger.json $HOME/$REPO/rest_doc
  - cd $HOME/$REPO/rest_doc
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add swagger.json
  - git commit -m "Travis auto-commit"
  - git push "https://${GH_TOKEN}@${GH_REPO}" master
