language: scala

jdk: oraclejdk8

scala:
   - 2.12.2

notifications:
    slack: whatsontoday:K22qCdNZ7GFj20Hrt8hU3DoS

env:
  global:
  - USER="whats-on-today-bot"
  - EMAIL="edgar.dorausch@whats-on.today"
  - REPO="WhatsOnToday.github.io"
  - GH_REPO="github.com/WhatsOnToday/WhatsOnToday.github.io.git"
  - secure: SxNayQUX/TU9GqbZfPIf8U0UnOY5vjk2FlTuNgPPU/IEFMOG6S7uXiufB0H5OCM/Yy1RFeQIDVlxdHGGDhU7VbiWjWIfricK0XcRfwpMZt3rweSJCaoiicgDEcUafCGdfYB0oJPrTjfOee+PkcCY721P6MUpIJ8esA4UR5uJCbMJftJ5VsaTuVltLX03qJKgCI9K2KDQai2QJ4WwkJtVk468xmou9znZn04HkViRiHKodtn3ODT/xK+5uenORMCa+AINcWPA6QH49L6LOpmEUIlmD72rnVQQlHzOEe0pqcQERplk2O2m6WeuYXrCQFj1X/Og4CDYak7GkVKZYA4x12woSy2TIjACM2mWKyJNOyDIbL1xh2bfp1IIz1P/FZQ4Eriud+oZw+Ics5Mrh965sLfdnWY7njI5kucKJYo3KpezGnMuyPHyDIn8I2zd4tR6/yjq2fJtMi/kTn+ie/Z4NSD/oh3bYCivWWyWdQan8Eg/HNvhafpoU3lLDHTnjgc22vLhlmwZkqKPwMfc82pbOXVzg+fl+4GpHb2lkxD/kIEqf4qNnjnrqd/JESKyUv7AmEKIjrIvJKG7iaaWZ+k0VZZl8iaeXRJWYrU3w3RUlB21Yq5rv0wDwLYbEZJoU3Y3fe/BKYnnIG+SDwyidCUlCJDaHvuUWrlTvefBC25b1qI=

services:
  - postgresql

before_script:
  - psql -c 'create database "WhatsOnDBTest";' -U postgres

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

after_success:
  - cd $TRAVIS_BUILD_DIR
  - sbt swagger
  # - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO} $HOME/$REPO
  - cp $TRAVIS_BUILD_DIR/target/swagger/swagger.json $HOME/$REPO/rest_doc
  - cd $HOME/$REPO/rest_doc
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add swagger.json
  - git commit -m "Travis auto-commit"
  - git push "https://${GH_TOKEN}@${GH_REPO}" master
