language: scala

jdk: oraclejdk8

scala:
   - 2.12.2

node_js:
  "6"

notifications:
    slack: whatsontoday:K22qCdNZ7GFj20Hrt8hU3DoS

env:
  global:
  - USER="whats-on-today-bot"
  - EMAIL="whats-on-today-bot@whats-on.today"
  - REPO="WhatsOnToday.github.io"
  - GH_REPO="github.com/WhatsOnToday/WhatsOnToday.github.io.git"
  - secure: isBfSQxqlC31yZiT0Jb9Oe/BOxKz7rEBDsMuYinKgQe+24w8Qm4GGKKiqnoqbihaP+MSwlSoL6kfm8XsD8Vq4VAZJqPJUiZ8ZWLkwqbNjCGbn9VsPSqg//bVmGYBAmZQnW/5dRyK0LCCneXkywvo9+G2TX5xzR1kMBEbTccQrJHi/DUzQp3q/UP3TECSAoQIR3wDZcUEWC/bjMjvKjYju++BHY5j3rUMCpmHnuxK9SJsIG8GwqmAqxZK/RYgpixd4p8Mfy2u0Eqgp+81Ek1BNb4ncq/dqe9KgeYNdpKZBEQPQc1Gb/AZaXSdZ/L1tDQiKCAB6ZxZTh2zldh9AMQp3ilQKBnJwjHB4Y49SinntYPNh/d0mDo1+EPeYCtLGO+ymnyPZSRbstoOyRMTis7iMNeFIFpCeL0HGoODcA1LJH0/bxpmB3Xi4rWSoMUSQkS/ZrQbf/VKL/gvGm37cLSRZSrCjiv7VM2dvdNt8ox0m7JLNkfiTQfeGubW/jTM94bqD/s5Avvl9boJObgm36E692lgjOFCuHP6OGKea9oqNiH9WojNYmI9gmf1uLfIwmpmLOVEAJsoeZvtKq3Th9O+TNUmQbxUrYw/0qm9/NDKQ0g5b2nzFfd4nT1LwEAVncyBCLX/XsQq72SxMGi/PtpxvrXLNFlphktMdiXXdXlBoJU=
services:
  - postgresql

before_script:
  - psql -c 'create database "WhatsOnDBTest";' -U postgres

script: ./travis/build.sh

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - ./webapp/node_modules/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

after_success: ./travis/success.sh
